export interface TempItem {
    cod_produto: string,
    nome_produto: string,
    emb: string,
    unidade: string,
    quantidade: number,
    desconto1: number,
    precoproduto: number,
    precoliquido: number,
    total_imposto: number,
    icms_destino: number,
    subtotal: number,
    peso: number,
    cubagem: number,
    volume: number,
    pesoTotal: number,
    cubagemTotal: number,
    volumeTotal: number,
    comissao: number,
    PrecoMedioQuilo: number,
    familia: string,
    nome_familia: string,
    grupo: string,
    nome_grupo: string
}